[project]
name = "ErisPulse-TelegramAdapter"
version = "4.1.0"
description = "ErisPulse的Telegram协议适配模块"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [ { name = "wsu2059", email = "wsu2059@qq.com" } ]
dependencies = []

[project.urls]
"homepage" = "https://github.com/ErisPulse/ErisPulse-TelegramAdapter"

[project.entry-points."erispulse.adapter"]
telegram = "TelegramAdapter:TelegramAdapter"
tg = "TelegramAdapter:TelegramAdapter"

[tool.setuptools.packages.find]
include = [ "TelegramAdapter" ]
